name: Hello Actions

on:
  push:
    branches: [main]


jobs:
  say-hello:
  run-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v4
    -name: Print a greeting
    run: echo "Hello, Github Actions! This run automatically on push."